-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema blog
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `RESOURCE_TYPE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RESOURCE_TYPE` (
  `RESOURCE_TYPE_ID` VARCHAR(8) NOT NULL,
  `DESCRIPTION` VARCHAR(64) NOT NULL,
  `CREATION_DATE` DATETIME NOT NULL,
  `MODIFICATION_DATE` DATETIME NULL,
  PRIMARY KEY (`RESOURCE_TYPE_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `FOLDER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FOLDER` (
  `FOLDER_ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(64) NOT NULL,
  `CREATION_DATE` DATETIME NOT NULL,
  `MODIFICATION_DATE` DATETIME NULL,
  PRIMARY KEY (`FOLDER_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RESOURCE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RESOURCE` (
  `RESOURCE_ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(64) NOT NULL,
  `CREATION_DATE` DATETIME NOT NULL,
  `MODIFICATION_DATE` DATETIME NULL,
  `RESOURCE_TYPE_ID` VARCHAR(8) NOT NULL,
  `FOLDER_ID` INT NOT NULL,
  `USERNAME` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`RESOURCE_ID`),
  CONSTRAINT `FK_RESOURCE_RESOURCE_TYPE1`
    FOREIGN KEY (`RESOURCE_TYPE_ID`)
    REFERENCES `RESOURCE_TYPE` (`RESOURCE_TYPE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RESOURCE_FOLDER1`
    FOREIGN KEY (`FOLDER_ID`)
    REFERENCES `FOLDER` (`FOLDER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RESOURCE_USER1`
    FOREIGN KEY (`USERNAME`)
    REFERENCES `USER` (`USERNAME`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_RESOURCE_RESOURCE_TYPE1_idx` ON `RESOURCE` (`RESOURCE_TYPE_ID` ASC);

CREATE INDEX `fk_RESOURCE_FOLDER1_idx` ON `RESOURCE` (`FOLDER_ID` ASC);

CREATE INDEX `fk_RESOURCE_USER1_idx` ON `RESOURCE` (`USERNAME` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
