-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema blog
-- -----------------------------------------------------

ALTER TABLE USER ENGINE=InnoDB;
ALTER TABLE ROLE ENGINE=InnoDB;
ALTER TABLE REL_USER_ROLE ENGINE=InnoDB;
ALTER TABLE PAGE ENGINE=InnoDB;
ALTER TABLE ENTRY ENGINE=InnoDB;
ALTER TABLE REL_ENTRY_TAG ENGINE=InnoDB;
ALTER TABLE TAG ENGINE=InnoDB;
ALTER TABLE PAGE ENGINE=InnoDB;

-- -----------------------------------------------------
-- Table `FOLDER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `FOLDER` (
  `FOLDER_ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(64) NOT NULL,
  `CREATION_DATE` DATETIME NOT NULL,
  `MODIFICATION_DATE` DATETIME NULL,
  PRIMARY KEY (`FOLDER_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RESOURCE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RESOURCE` (
  `RESOURCE_ID` INT NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(64) NOT NULL,
  `CREATION_DATE` DATETIME NOT NULL,
  `MODIFICATION_DATE` DATETIME NULL,
  `FOLDER_ID` INT NOT NULL,
  `USERNAME` VARCHAR(32) NOT NULL,
  `CONTENT_TYPE` VARCHAR(64) NOT NULL,
  `SIZE` DOUBLE NOT NULL,
  PRIMARY KEY (`RESOURCE_ID`),
  CONSTRAINT `FK_RESOURCE_FOLDER`
    FOREIGN KEY (`FOLDER_ID`)
    REFERENCES `FOLDER` (`FOLDER_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_RESOURCE_USER`
    FOREIGN KEY (`USERNAME`)
    REFERENCES `USER` (`USERNAME`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_RESOURCE_FOLDER_idx` ON `RESOURCE` (`FOLDER_ID` ASC);

CREATE INDEX `fk_RESOURCE_USER_idx` ON `RESOURCE` (`USERNAME` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;