-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Table `RESOURCE_TYPE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RESOURCE_TYPE` (
  `RESOURCE_TYPE_ID` VARCHAR(8) NOT NULL,
  `DESCRIPTION` VARCHAR(64) NOT NULL,
  `CREATION_DATE` DATETIME NOT NULL,
  `MODIFICATION_DATE` DATETIME NULL,
  PRIMARY KEY (`RESOURCE_TYPE_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RESOURCE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RESOURCE` (
  `RESOURCE_ID` INT NOT NULL,
  `NAME` VARCHAR(64) NOT NULL,
  `CREATION_DATE` DATETIME NOT NULL,
  `MODIFICATION_DATE` DATETIME NULL,
  `RESOURCE_TYPE_ID` VARCHAR(8) NOT NULL,
  `DATA` BLOB(2048) NOT NULL,
  PRIMARY KEY (`RESOURCE_ID`),
  CONSTRAINT `FK_RESOURCE_RESOURCE_TYPE1`
    FOREIGN KEY (`RESOURCE_TYPE_ID`)
    REFERENCES `RESOURCE_TYPE` (`RESOURCE_TYPE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_RESOURCE_RESOURCE_TYPE1_idx` ON `RESOURCE` (`RESOURCE_TYPE_ID` ASC);


-- -----------------------------------------------------
-- Table `REL_ENTRY_RESOURCE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `REL_ENTRY_RESOURCE` (
  `ENTRY_ID` INT NOT NULL,
  `RESOURCE_ID` INT NOT NULL,
  PRIMARY KEY (`ENTRY_ID`, `RESOURCE_ID`),
  CONSTRAINT `fk_ENTRY_has_RESOURCE_ENTRY1`
    FOREIGN KEY (`ENTRY_ID`)
    REFERENCES `ENTRY` (`ENTRY_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ENTRY_has_RESOURCE_RESOURCE1`
    FOREIGN KEY (`RESOURCE_ID`)
    REFERENCES `RESOURCE` (`RESOURCE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `fk_ENTRY_has_RESOURCE_RESOURCE1_idx` ON `REL_ENTRY_RESOURCE` (`RESOURCE_ID` ASC);

CREATE INDEX `fk_ENTRY_has_RESOURCE_ENTRY1_idx` ON `REL_ENTRY_RESOURCE` (`ENTRY_ID` ASC);


-- -----------------------------------------------------
-- Table `REL_PAGE_RESOURCE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `REL_PAGE_RESOURCE` (
  `PAGE_ID` INT NOT NULL,
  `RESOURCE_ID` INT NOT NULL,
  PRIMARY KEY (`PAGE_ID`, `RESOURCE_ID`),
  CONSTRAINT `fk_PAGE_has_RESOURCE_PAGE1`
    FOREIGN KEY (`PAGE_ID`)
    REFERENCES `PAGE` (`PAGE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PAGE_has_RESOURCE_RESOURCE1`
    FOREIGN KEY (`RESOURCE_ID`)
    REFERENCES `RESOURCE` (`RESOURCE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_PAGE_has_RESOURCE_RESOURCE1_idx` ON `REL_PAGE_RESOURCE` (`RESOURCE_ID` ASC);

CREATE INDEX `fk_PAGE_has_RESOURCE_PAGE1_idx` ON `REL_PAGE_RESOURCE` (`PAGE_ID` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
